import {useState} from 'react';
import {Scissors,Trash2,Save} from 'lucide-react';
import {Modal} from './Modal';
import {ShortcutInput} from './ShortcutInput';
import {StoragePanel} from './StoragePanel';
import {RemotePanel} from './RemotePanel';
import {api} from './api';
import type {Profile,Sound,State} from './types';

export function NameDialog({title,initial='',onClose,onSave}:{title:string;initial?:string;onClose:()=>void;onSave:(name:string)=>Promise<void>}) {
  const [name,setName]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');
  return <Modal title={title} onClose={onClose} busy={busy}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave(name.trim());onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{error&&<p role="alert" className="form-error">{error}</p>}<label className="field">Name<input autoFocus value={name} maxLength={80} required onChange={e=>setName(e.target.value)}/></label><div className="modal-footer"><button type="button" className="secondary" onClick={onClose} disabled={busy}>Cancel</button><button className="primary" disabled={busy||!name.trim()}>Save</button></div></form></Modal>;
}

export function TileDialog({profile,index,sounds,onClose,onSaved,onEdit}:{profile:Profile;index:number;sounds:Sound[];onClose:()=>void;onSaved:()=>Promise<void>;onEdit:(s:Sound)=>void}) {
  const current=profile.tiles[index];
  const sortedSounds=[...sounds].sort((a,b)=>a.name.localeCompare(b.name,undefined,{sensitivity:'base',numeric:true}));
  const [soundId,setSoundId]=useState(current?.sound_id??sortedSounds[0]?.id??'');
  const [label,setLabel]=useState(current?.label??''),[color,setColor]=useState(current?.color??'#c4ed83');
  const [volume,setVolume]=useState(current?.volume??1),[shortcut,setShortcut]=useState(current?.shortcut??'');
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const sound=sounds.find(s=>s.id===soundId);
  async function save(remove=false) {setBusy(true);setError('');try{await api(`/sets/${profile.id}/tiles/${index}`,remove?{sound_id:null}:{sound_id:soundId,label,color,volume,shortcut});await onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <Modal title={current?'Tile settings':'Add a sound tile'} onClose={onClose} busy={busy}>{error&&<p role="alert" className="form-error">{error}</p>}<label className="field">Sound<select value={soundId} onChange={e=>setSoundId(e.target.value)}>{!sound&&<option value={soundId}>Choose a sound</option>}{sortedSounds.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field">Tile label<input value={label} maxLength={120} placeholder={sound?.name??'Use the sound name'} onChange={e=>setLabel(e.target.value)}/></label><div className="fields two"><label className="field">Colour<input className="color-field" type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label className="field">Clip volume · {Math.round(volume*100)}%<input type="range" min="0" max="100" value={Math.round(volume*100)} onChange={e=>setVolume(+e.target.value/100)}/></label></div><ShortcutInput label="Global shortcut" value={shortcut} onChange={setShortcut}/><p className="form-hint">Shortcuts are paused while this dialog is open. Use a modifier such as Ctrl, or a function key.</p>{sound&&<button className="secondary" onClick={()=>{onClose();onEdit(sound)}}><Scissors size={16}/>Trim this sound</button>}<div className="modal-footer">{current&&<button className="danger-text" disabled={busy} onClick={()=>void save(true)}><Trash2 size={16}/>Remove tile</button>}<button className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy||!sound} onClick={()=>void save()}><Save size={16}/>Save tile</button></div></Modal>;
}

export function SetSettings({profile,state,onClose,onSaved,onRemove,initialTab='set'}:{initialTab?:'set'|'storage'|'remote';profile:Profile;state:State;onClose:()=>void;onSaved:()=>Promise<void>;onRemove:()=>void}) {
  const [tab,setTab]=useState<'set'|'storage'|'remote'>(initialTab);
  const [name,setName]=useState(profile.name),[rows,setRows]=useState(profile.rows),[columns,setColumns]=useState(profile.columns);
  const [mode,setMode]=useState(profile.playback_mode),[enabled,setEnabled]=useState(state.sets.hotkeys_enabled),[stop,setStop]=useState(state.sets.stop_shortcut);
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  async function save() {setBusy(true);setError('');try{await api(`/sets/${profile.id}/settings`,{name,rows,columns,playback_mode:mode,hotkeys_enabled:enabled,stop_shortcut:stop});await onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <Modal title="Settings" onClose={onClose} busy={busy}><nav className="view-tabs settings-tabs" aria-label="Settings sections"><button disabled={busy} className={tab==='set'?'active':''} onClick={()=>setTab('set')}>Set & shortcuts</button><button disabled={busy} className={tab==='storage'?'active':''} onClick={()=>setTab('storage')}>Storage</button><button disabled={busy} className={tab==='remote'?'active':''} onClick={()=>setTab('remote')}>Remote control</button></nav>{tab==='remote'?<RemotePanel busy={busy} onBusy={setBusy}/>:tab==='storage'?<StoragePanel state={state} busy={busy} onBusy={setBusy} onSaved={onSaved}/>:<>{error&&<p role="alert" className="form-error">{error}</p>}<label className="field">Set name<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><div className="fields two"><label className="field">Rows<input type="number" min="1" max="12" value={rows} onChange={e=>setRows(+e.target.value)}/></label><label className="field">Columns<input type="number" min="1" max="12" value={columns} onChange={e=>setColumns(+e.target.value)}/></label></div><p className="form-hint">Extra sounds stay on additional pages when you shrink the grid.</p><label className="field">When another sound starts<select value={mode} onChange={e=>setMode(e.target.value as 'replace'|'overlap')}><option value="replace">Replace the previous sound</option><option value="overlap">Allow sounds to overlap</option></select></label><label className="check-field"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Enable global shortcuts</label><ShortcutInput label="Stop all shortcut" value={stop} onChange={setStop}/><p className="form-hint">Only the active set's sound shortcuts are registered. Stop all applies to every set.</p><div className="modal-footer">{Object.keys(state.sets.profiles).length>1&&<button className="danger-text" disabled={busy} onClick={onRemove}><Trash2 size={16}/>Remove set</button>}<button className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy} onClick={()=>void save()}>Save settings</button></div></>}</Modal>;
}
